### ISSUE TITLE
Add bounties page

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-website#17]
Add a page describing the available Lisk bounties in order to encourage community participation.

**Comment by karmacoma** [comment]
Previously incomplete work moved here: https://github.com/LiskHQ/lisk-website/tree/17-add_bounties

**Comment by schabluk** [comment]
@karmacoma Page not found. Is this private?

**Comment by karmacoma** [comment]
@schabluk Never merged. It will be revisited in the new website.
