### ISSUE TITLE
Repoint or Remove old Rocketchat Links

### ISSUE THREAD

**Issue by jfernanz** [LiskHQ/lisk-website#25]
http://downloads.lisk.chat/rocketchat.exe

http://downloads.lisk.chat/rocketchat.dmg

http://downloads.lisk.chat/rocketchat_amd64.deb

**Comment by Isabello** [comment]
Links were updated.

Closed by commit: https://github.com/LiskHQ/lisk-website/commit/a66b001f2da73eb6c8ce6c096a38d45fe5217bfb
