### ISSUE TITLE
Set up redirection wiki.lisk.io -> https://github.com/LiskHQ/lisk-wiki/wiki

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-website#26]

**Comment by Isabello** [comment]
We are moving away from the wiki so this is a wont fix but ill leave open as a reminder for the repoint to the new solution

**Comment by Isabello** [comment]
Closed via https://github.com/LiskHQ/lisk-website/commit/444f1f7d31b057ebe701934034ecb2a025dc679d#diff-0364f57fbff2fabbe941ed20c328ef1aR155
