### ISSUE TITLE
Move Lisk.io behind Cloudflare

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-website#34]
To avoid possible downtime for static/mostly static content of Lisk.io i propose to migrate it behind free Cloudflare plan which will be more than enough.

**Comment by Isabello** [comment]
This is also not an issue that belongs on github.

**Comment by MaxKK** [comment]
We have already evaluated Cloudflare and are not convinced with their services for a blockchain startup. There are other solutions which might work better for us.

Thank you for your contribution, we will discuss internally. As this is a non-code related issue it was right to close it. As you know you can always contact us through our other channels.
