### ISSUE TITLE
'View All Results' for the search function in documentation leads to 404 

### ISSUE THREAD

**Issue by hcs0** [LiskHQ/lisk-website#46]
In the documentation pages: https://docs.lisk.io/docs

If I search for a term, I am able to see the first three search results (ie ``secret``). 
When I click on the ``View All Results`` link, it leads me to a 404 page.

**Comment by MaxKK** [comment]
Thank you @hcs0 , 

This is outside of our control as we are using readme.io for our documentation. However, can you please check if it's working again? I have just tried it and everything works perfectly.

Thank you.


Best,
Max

**Comment by hcs0** [comment]
Thanks! Working now https://docs.lisk.io/v1.2.1/search?q=installation
