### ISSUE TITLE
Current download of Lisk Nano point to 0.1.1 instead current 0.1.2

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-website#6]
I've noticed that 
<img width="539" alt="screen shot 2016-12-04 at 12 57 53" src="https://cloud.githubusercontent.com/assets/9548618/20865984/4d00f760-ba21-11e6-96b8-cd65537b1d94.png">
Points to
https://downloads.lisk.io/lisk-nano/0.1.1/lisk-nano-0.1.1.dmg
instead
https://downloads.lisk.io/lisk-nano/0.1.2/lisk-nano-0.1.2.dmg

It seems it has been updated here: https://github.com/LiskHQ/lisk-website/blob/development/app.js#L141

But not uploaded to server, while https://downloads.lisk.io/lisk-nano/0.1.2/lisk-nano-0.1.2.dmg exists.

**Comment by Isabello** [comment]
sorry i wasnt around to update the website, its done now.
